### ISSUE TITLE
Possible memory leak when closing consumers

### ISSUE THREAD

**Issue by hugomallet** [versatica/mediasoup-client#125]
Hello,

Environment: Chrome 84.0.4147.89 / macOS

When i close a consumer, i still see its track in heap snapshots.
It looks like that they are retained in the corresponding RTCRtpReceiver which is retained in RTCPeerConnection and RTCRtpTransceiver (retained in _mapMidTransceiver).

It seems to be the same in mediasoup-demo. Can you reproduce ? 

Looking at the code, i see that transceivers are never deleted from the _mapMidTransceiver.

Thanks,

**Comment by ibc** [comment]
This is how SDP works (unfortunately). When disabling/closing a SDP `m=` section, the `m=` section is not removed but just disabled. Since we (mediasoup-client) construct the remote SDP we need to retain those closed m= sections (this is, we need to keep the corresponding transceiver objects into our map.
