### ISSUE TITLE
Firefox handler doesn't respect RtpSendParameter.encodings if only 1 encoding is specified 

### ISSUE THREAD

**Issue by andrewlin12** [versatica/mediasoup-client#145]
## Bug Report
Firefox does not respect `encodings` if only a single encoding specification is passed to `Transport.produce`.

### Your environment

- Operating system: MacOS
- Browser version: Firefox 83
- mediasoup-client version: 3.6.21

### Issue description
In the Firefox60 handler, it looks like `encodings` is ignored if length is 1: https://github.com/versatica/mediasoup-client/blob/v3/src/handlers/Firefox60.ts#L307. I tested a modification to initialize `reverseEncodings` to `encodings` and Firefox started respecting the parameters.

**Comment by ibc** [comment]
BTW note that Firefox is not yet spec compliant regarding encodings:

https://github.com/versatica/mediasoup-client/blob/v3/src/handlers/Firefox60.ts#L341

However we do the trick there. If true that we should consider single encoding case and respect them. It should be done here:

https://github.com/versatica/mediasoup-client/blob/v3/src/handlers/Firefox60.ts#L317

If there are encodings but just one we should assign them to reverseEncodings there.

Can you do a PR? Otherwise I'll just fix it eventually when I get time.

**Comment by andrewlin12** [comment]
FYI, I posted a possible fix here: https://github.com/versatica/mediasoup-client/pull/146

**Comment by ibc** [comment]
Yup, thanks. Will review tomorrow.
