### ISSUE TITLE
Error with Firefox 59 "Developer edition"

### ISSUE THREAD

**Issue by Demivan** [versatica/mediasoup-client#18]
```InvalidSessionDescriptionError: Invalid description, mid length greater than 16 unsupported until 2-byte rtp header extensions are supported in webrtc.org```

Firefox limited `mid` length to 16 characters: https://github.com/mozilla/gecko-dev/commit/69d270acdf3aa8b7a96c5e963c93c342d9cb4cbb

Can `mid` be made shorter?

**Comment by ibc** [comment]
Interesting. This is because the value of `a=mid` is also supposed to be carried within then `MID` RTP header extension which can be 1-byte or 2-byte as per spec, but Firefox just implements the 1-byte header extensions.

Yes, I will change the `mid` value to ensure they fit into 16 chars.

Thanks for reporting.

**Comment by ibc** [comment]
Fixed in mediasoup-client 2.0.11
