### ISSUE TITLE
Firefox 59 does not respect msids from offer

### ISSUE THREAD

**Issue by artushin** [versatica/mediasoup-client#21]
Reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1437980

Relevant snippet from `handlers/Firefox50.js`

```
			.then(() =>
			{
				const newRtpReceiver = this._pc.getReceivers()
					.find((rtpReceiver) =>
					{
						const { track } = rtpReceiver;

						if (!track)
							return false;

						return track.id === consumerInfo.trackId;
					});

				if (!newRtpReceiver)
					throw new Error('remote track not found');

				return newRtpReceiver.track;
			});
```

newRtpReceiver track id will not match consumerInfo trackId because Firefox no longer uses the msid from the offer as the track id.

**Comment by ibc** [comment]
Thanks, confirmed. This may be due the new "Transceiver" based API and latest spec discussions that state that the `id` of the remote `track` should not be a value generated by the remote via the `a=msid` attribute in the remote SDP.

I mean: the behavior of Firefox >= 59 could be correct. So I'll figure out another way to handle it.

**Comment by ibc** [comment]
This is fixed in mediasoup-client 2.0.13. Many thanks for reporting!

**Comment by ibc** [comment]
However, even if this issue is fixed, in my tests with Firefox Nightly 60 I get a new error: once the remote closes an audio/video Producer or adds a new one (so `setRemoteDescription()` is called on the receiving peerconnection in Firefox) all the remote audio/video tracks in Firefox get frozen (no more audio/video is rendered).

This is probably a new bug in Firefox. But since this is still Nightly... who knows.

**Comment by kreativ-software** [comment]
Will there be a fix for the 1.x branch as well?

**Comment by ibc** [comment]
We don't have time to maintain the 1.x version.

**Comment by kreativ-software** [comment]
Okay. I'll try to update to v2. Thanks for the quick response.
