### ISSUE TITLE
Mediasoup client is synchronizing all the producers even if they belong to different streams

### ISSUE THREAD

**Issue by ggarber** [versatica/mediasoup-client#233]
## Bug Report

mediasoup-client (the handlers) use a single fake mediastream to associate all the tracks being sent.    That means that the SDP generated includes a msid with the same streamID for all the sent tracks and that the receiver will try to play in sync all those tracks.

This is perfect when you only publish 1 stream with 2 media tracks/producers but when having multiple cameras or camera and screensharing this is forcing the receiver to synchronize two completely independent streams.   That can create higher delays than needed.

The mediasoup-client handlers should provide a way to preserve the streams associations when calling peerConnection.addTrack API.

Close this ticket if i'm wrong but that's how i think it is working today based on the code and some testing done with screensharing.

### Your environment

- mediasoup-client version: 3.6.6

**Comment by ibc** [comment]
This report is invalid because we don't signal the id of the local MediaStream from client to server, so Consumers don't know about it at all. mediasoup-client creates a `a=msid` based on cname which is the same for all consumers whose producer was created in the same sending transport.

<img width="681" alt="CleanShot-2022-12-09-at-13 17 55@2x" src="https://user-images.githubusercontent.com/16191/206701154-e03f7fea-045f-4c6b-a87e-dd22a939f976.png">

<img width="664" alt="CleanShot-2022-12-09-at-13 18 43@2x" src="https://user-images.githubusercontent.com/16191/206701163-cb2bb877-64ac-4d41-9dec-e43825997da9.png">

**Comment by ggarber** [comment]
"This report is invalid because we don't signal the id of the local MediaStream from client to server, so Consumers don't know about it at all. "

That's exactly the bug that i was reporting :)

Consumers don't know about it so they use the same msid/cname for completely unrelated streams (screensharing and camera for example) coming from the same sending transport.

**Comment by ibc** [comment]
> Consumers don't know about it so they use the same msid/cname for completely unrelated streams (screensharing and camera for example) coming from the same sending transport.

So do we agree that this (same msid/cname) just happens in consumers originated from producers of the same remote sender? Assuming yes, then your concern is that in receiver side we are telling libwebrtc to sync your webcam and screensharing streams, right?

AFAIK libwebrtc can just sync one audio and one video, so I understand your concern. We don't want to sync your audio with your screen sharing. Is it?

**Comment by ggarber** [comment]
Yes! Exactly what you said.

**Comment by ibc** [comment]
Unfortunately there is stuff involved in mediasoup side as well. Grep `/cname/i` in `Transport.ts` in mediasoup side.

I'll leave this open but not sure about ETA for a solution. Need to think about it.

**Comment by ibc** [comment]
Surprise: https://github.com/versatica/mediasoup-client/pull/234

**Comment by ibc** [comment]
Done in mediasoup-client 3.6.68 and documented in https://mediasoup.org/documentation/v3/mediasoup-client/api/#ConsumerOptions

**Comment by ggarber** [comment]
Thank you!   I'll try to use it asap.

FYC I think it would be great in the future if the Offer sent from the producer side includes different streamIds in the msid lines for different streams.     It looks more "correct" and could simplify the creation of consumers in the consumer side, but your approach LGTM.

Thank you!

**Comment by ibc** [comment]
> FYC I think it would be great in the future if the Offer sent from the producer side includes different streamIds in the msid lines for different streams. It looks more "correct" and could simplify the creation of consumers in the consumer side

I expected this comment/request :)

Nope. Such a `streamId` (the first component in the `a=msid` attribute of the m section of the SDP) is completely useless in mediasoup side. It's not even standard at all. libwebrtc decided to sync based on it because `¯\_(ツ)_/¯`. Anyway, that's irrelevant. The thing here is that we don't need to signal it from client to mediasoup and, if you want to do it, you can add `streamId` into `appData` when calling `transport.produce()` in mediasoup-client and then read it when you send the consuming parameters to receivers.

Anyway, the first component of the `a=msid` attribute is the `id` of the `MediaStream` (which is something that should not exist since it has zero impact at the wire). If you call `gUM()` first to obtain mic audio and later call `gUM()` again to get video, you obtain 2 different `MediaStreams` and the first component of their `a=msid` won't even match so they won't be valid for consumers to sync them.

Completely against signaling things to mediasoup server which are not used in mediasoup at all.

**Comment by jmillan** [comment]
@ggarber, did you observe any specific problems (delay related, I guess) that lead you to look into this? Any specifics?

**Comment by ibc** [comment]
> @ggarber, did you observe any specific problems (delay related, I guess) that lead you to look into this? Any specifics?

Actually it's well known that libwebrtc can just synchronize 1 audio + 1 video.

**Comment by jmillan** [comment]
>> @ggarber, did you observe any specific problems (delay related, I guess) that lead you to look into this? Any specifics?

> Actually it's well known that libwebrtc can just synchronize 1 audio + 1 video.

This is not answering my question at all :-), plus I'm sure only @ggarber and his team know the answer to my specific question. This is why I'm asking him specificly.

**Comment by ggarber** [comment]
> t answering my question at all :-), plus I'm sure only @ggarber and his team know the answer to my specific question. This is why I'm asking him specificly.

@jmillan We have complains of lip sync issues(audio not in sync with video) from customers from time to time.  This is something that I have seen in other apps like Google Meet sometimes but it looks like more frequente in our mediasoup-based application.  

In case it helps the two issues i've seen with mediasoup so far that I think lead to sync issues are:
- zeroRtpOnPause option: That forces a renegotiation and we think that muting and unmuting creates lip sync issues for some seconds when that option is enabled.
- the issue reported here

**Comment by jmillan** [comment]
> zeroRtpOnPause

We have seen this too. Very likely because resuming (after disabling it) the encoder takes time, which may generate an audio delay.


Thanks con the comments @ggarber
