### ISSUE TITLE
Common code in handlers

### ISSUE THREAD

**Issue by Demivan** [versatica/mediasoup-client#25]
Chrome55 and Chrome67 handlers, as well as two Firefox handlers have a lot of common code.
Shared code can be moved out to some "abstract" base class with overrides for methods that are actually different.
Are there any plans to cleanup handlers?
I can do a pull request if you are fine with these changes.

**Comment by ibc** [comment]
The idea behind handlers is that, once working, there is no need to change them. I don't want to share too much code between them because, at the end, that makes things harder to manage. Anyway, part of the code is already shared (the PlanB / UnifiedPlan SDP handlers, SDP and ORTC utils, etc).

In the future, we may have a `WebRTC10Handler.js` valid for the latest versions of Chrome, Firefox and Safari, but not yet.
