### ISSUE TITLE
utils.clone fails with Proxy Objects in `mediasoup-client` After v3.6.100

### ISSUE THREAD

**Issue by Berenger** [versatica/mediasoup-client#307]
###  Environment

- mediasoup-client version: 3.6.101+
- vueJS version: 3.2
- viteJS version: 5.1
- node version: 18.19.1
- npm version: 10.2.4

### Issue description
Heelo!

We are integrating `mediasoup-client` into a VueJS project that uses ViteJS. After upgrading to `mediasoup-client` version 3.6.101+, we encountered a problem with the `utils.clone` function, which no longer works as expected in some cases.

The `utils.clone` function throws an error when attempting to clone a value of type `Proxy`. We suspect this issue is related to how ViteJS handles certain objects, but the exact cause remains unidentified.

Here’s the problematic function in `mediasoup-client`:

```js
export function clone<T>(value: T): T {
    if (value === undefined) {
        return undefined as unknown as T;
    } else if (Number.isNaN(value)) {
        return NaN as unknown as T;
    } else if (typeof structuredClone === 'function') {
        // Available in Node >= 18.
        return structuredClone(value);
    } else {
        return JSON.parse(JSON.stringify(value));
    }
}
```
In our development environment, when `value` is a Proxy object, this function throws the following error:

```
Uncaught (in promise) DOMException: Proxy object could not be cloned.
```

This issue occurs during calls like the following, which can be found in various handlers, such as in `mediasoup-client/lib/handlers/Firefox120.js`:

```js
const sendingRtpParameters = utils.clone(this._sendingRtpParametersByKind[track.kind]);
```

#### Stack Trace

Here’s an excerpt of the error trace:

```
Uncaught (in promise) DOMException: Proxy object could not be cloned.
clone  utils.js:18  
send  Firefox120.js:251  
produce  Transport.js:324  
execute  index.js:172  
push  index.js:128  
push  index.js:62  
produce  Transport.js:282  
sendCameraStreams  StreamSend.vue:648  
connectAndStreamDevice  StreamSend.vue:623  
11  StreamSend.vue:168  
callWithErrorHandling  runtime-core.esm-bundler.js:192  
callWithAsyncErrorHandling  runtime-core.esm-bundler.js:199  
emit  runtime-core.esm-bundler.js:712  
createSetupContext/get emit/<  runtime-core.esm-bundler.js:7811  
handleClick  button.vue:103  
callWithErrorHandling  runtime-core.esm-bundler.js:192  
callWithAsyncErrorHandling  runtime-core.esm-bundler.js:199  
invoker  runtime-dom.esm-bundler.js:681
```
### Expected Behavior

The `utils.clone` function should handle Proxy objects gracefully, or at the very least provide a more informative error.

Thank you in advance for your assistance in resolving this issue. We appreciate your help!

**Comment by ibc** [comment]
This was already reported in the past and discarded. The application should NOT pass Proxy objects to mediasoup-client API but pure JS objects. I don't know Vue but, for example, in MobX there are also Proxy objects everywhere and MobX exposes a toJs(proxy) to convert a Proxy object into a pure JS object. I am pretty sure there is something similar in Vue and that's what the application must use before passing objects to mediasoup-client API.

I am closing this ticket because it's the very same we discussed some months ago in another similar ticket (or maybe in the forum, I can't remember). The utils.clone() function used `structuredClone()` JS function which is the most efficient way to clone objects or arrays and definitely we want to use it for performance reasons.
