### ISSUE TITLE
mediasoup-client is not supported react native ?

### ISSUE THREAD

**Issue by nullarch** [versatica/mediasoup-client#78]
I installed mediasoup-client v3 on react native. and then I made test envirment but I got some of errors

First error: 
In mediasoup client sdk react native handler.js doesn't import webrtc sdk

Second:
SendHandler.send() function can not refer to variable track.streamReactTag 

Third:
getRtpEncodings function assumes that sdp includes the ssrc field. But error occurs because some of offer sdp cases does not include ssrc field.

Could you let me know how much progress media snoup client has made to support react native?

**Comment by ibc** [comment]
> In mediasoup client sdk react native handler.js doesn't import webrtc sdk

I don't know which the "webrtc sdk" is. If you mean `react-native-webrtc`, it's not properly supported yet: https://github.com/versatica/mediasoup-client/issues/5

In short, `react-native-webrtc` is far from good (check the issue). This just refers to iOS since WebRTC is natively supported in Android's Chrome webview.

> SendHandler.send() function can not refer to variable track.streamReactTag

Related to first bullet.

> Could you let me know how much progress media snoup client has made to support react native?

It should work in Android. It may work in iOS with minor modifications to `react-native-webrtc` as told in #5.

Closing since there is already an issue for suporting `react-native-webrtc` (which probably won't happen since we may go for another approach: creating a `react-native-madiasoup-client` that uses [libmediasoupclient](https://github.com/versatica/libmediasoupclient)) internally).

**Comment by philjoseph** [comment]
WebRTC is now supported on iOS as of iOS 12, see https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8. Does it change your plan regarding react-native support ?

**Comment by ibc** [comment]
react-native does NOT use Safari or Chrome webview, so that's completely unrelated.

**Comment by philjoseph** [comment]
You're 100% right, I was just confused by your comment 

> In short, `react-native-webrtc` is far from good (check the issue). This just refers to iOS since WebRTC is natively supported in Android's Chrome webview.

since now Safari is support WebRTC as well, even on iOS.

**Comment by ibc** [comment]
My fault. That just applies to Cordova which uses webviews. react-native does not use them.
