### ISSUE TITLE
Module suitable for Node.js Client?

### ISSUE THREAD

**Issue by akashbudhia** [versatica/mediasoup-client#9]
Can mediasoup client sdk be used by a Node.js Client Application? So audio from a browser can be streamed in real-time to this node.js client? Signalling in this case handled by a central server (another Node.js application).

In my case the Node.js client application will be running on a Raspberry Pi.

**Comment by ibc** [comment]
This is very complex. If the browser needs to signal audio/video to a mediasoup-client running in a Node environment, it means that another signaling mechanism is required between such a browser and the mediasoup-client instance.

Honestly I don't get the picture you mean. I don't fully understand why running mediasoup-client in your browser is not a feasible solution.

If you wish, let's please move this discussion to the mediasoup mailing list (since this is not an issue in the code).

**Comment by akashbudhia** [comment]
Hi, my question is same as what the community have asked here https://stackoverflow.com/questions/18872712/node-js-webrtc-client

In my browser application I want logged i user to be able to speak in his mic and in real-time the audio stream be received by a node.js client application(with no UI) which can play this audio through a loudspeaker connected to it.

**Comment by ibc** [comment]
I understand the point, but it's not feasible right now.
